version: '3.8'

services:
  roborall:
    image: roborally_app
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-postgres!};Server=roborally_db;Port=5432;Database=${POSTGRES_DB:-roborally_db};
    depends_on:
      - roborally_db

  roborally_db:
    image: postgres:15
    container_name: roborally_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-roborally_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres!}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: